headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\users\\akhil\\hss-website\\api"
functionsDirectoryOrigin = "config"

[functions]

[functions."*"]
node_bundler = "esbuild"

[build]
publish = "C:\\users\\akhil\\hss-website"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'No build required - static site with serverless functions'"
functions = "C:\\users\\akhil\\hss-website\\api"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]